### ISSUE TITLE
Can we use `fast_numpy_load()` to load numpy array saved with regular `np.save()` ?

### ISSUE THREAD

**Issue by CharlieCheckpt** [divideconcept/fastnumpyio#1]
Hello @divideconcept,

Thanks for this nice piece of code !

Is it possible to use your function `fast_numpy_load()` to load already saved numpy arrays saved with the numpy function `np.save()` ?

If yes, can you share a way to do this ? I am not sure how can I get the object `data` that should be passed as input to this function.

**Comment by divideconcept** [comment]
Hi @CharlieCheckpt now you can, check the latest commits and updated README :)
fastnumpyio.load() and fastnumpyio.save() now behaves like the regular numpy.load() and numpy.save() (but faster)
