### ISSUE TITLE
Slower with big arrays?

### ISSUE THREAD

**Issue by cTatu** [divideconcept/fastnumpyio#3]
Hi, I was wondering if we could use your fast array functions for our project. I tried running the benchmark present in the `__main__` function with one of our array `testarray=np.random.rand(10_000_000, 300).astype('float32')` and using `iterations=5`. These were the results:
```
numpy.save: 0:00:23.873892
fastnumpyio.save: 0:00:39.867552
fastnumpyio.pack: 0:00:39.946588
```

Is this expected?
I think the reason could be that `array.tobytes()` creates a copy.

Thank you

**Comment by divideconcept** [comment]
Good diagnostic, I replaced array.tobytes() by array.data and it significantly sped up fastnumpyio.save and fastnumpyio.pack, both for large and small arrays !

Before with large arrays:
numpy.save: 0:00:11.338604
fastnumpyio.save: 0:00:18.967618
fastnumpyio.pack: 0:00:23.542093

After with large arrays:
numpy.save: 0:00:11.853167
fastnumpyio.save: 0:00:10.711883
fastnumpyio.pack: 0:00:07.997765

Before with small arrays:
numpy.save: 0:00:00.704817
fastnumpyio.save: 0:00:00.357014
fastnumpyio.pack: 0:00:00.299592

After with small arrays:
numpy.save: 0:00:00.729113
fastnumpyio.save: 0:00:00.155620
fastnumpyio.pack: 0:00:00.136568

The commit is now pushed on the repo !

**Comment by cTatu** [comment]
Nice thank you very much for the fast response!

I wanted to show you a little benchmark I run in one of our old systems. Here the graph shows that splitting an array in multiple sub-arrays (chunks) and writing/reading each one in separate files gives more performance. I think is because of the [blk-mq](https://www.thomas-krenn.com/en/wiki/Linux_Multi-Queue_Block_IO_Queueing_Mechanism_(blk-mq)_Details) but I can't confirm it yet.
![image](https://github.com/divideconcept/fastnumpyio/assets/37102803/91fe8cc4-b691-4011-b632-c4decbd6cbc1)

Knowing this, do you think it could be feasible to write every arrays in chunks as separate files and somehow bundle them together in order to treat them as a single file?

**Comment by divideconcept** [comment]
@cTatu So I better understand, it looks like you don't really care about the numpy file format itself, you just want to be able to save numpy arrays on disk and load them the fastest possible way, right ?

For people who don't care about the numpy file format itself I've added this extra .pack and .unpack function (it's even more compact and faster), but if I understand your needs right, what you would need is a .filepack function which would take parameters like: filename, array, chunksize and automatically generate:
myfile.000, myfile.001, myfile.002...
and then the corresponding .fileunpack function that would read those separate files and reconstruct a numpy array from it.

Correct ?
